import type { Metadata } from "next";
import { Box, Container, Theme } from "@radix-ui/themes";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Theme accentColor="green">
          <Box px="2">{children}</Box>
        </Theme>
      </body>
    </html>
  );
}
